# 运行环境
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 80
  servlet:
    context-path: /aiuas/

logging:
  level:
    com.chinobot: debug
    org.springframework.web: info
    org.springframework.transaction: debug
    org.mybatis: debug
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
